In [2]:
import numpy as np

a = np.array([1,2,3,4])

print(a)

[1 2 3 4]


In [13]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print("Vectorised Version: c = "+str(c)+" time = " + str(1000*(toc-tic))+"ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print("For Loop Version: c = "+str(c)+" time = " + str(1000*(toc-tic))+"ms")


Vectorised Version: c = 250139.56552649927 time = 0.9992122650146484ms
For Loop Version: c = 250139.56552649642 time = 610.4080677032471ms


In [15]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[ 0.07937549 -0.10099499 -0.09118988]
 [-1.02575163  0.79694288 -0.96408369]
 [ 0.24653073  0.54189098  0.10270722]]
